# Generated by Django 3.2.8 on 2022-03-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='postAchivements',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('veiws', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='thubnail_images')),
                ('title', models.CharField(max_length=200)),
                ('categories', models.CharField(choices=[('World', 'World'), ('Enviroment', 'Enviroment'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Opinion', 'Opinion'), ('Science', 'Science'), ('Health', 'Health'), ('Style', 'Style'), ('Travel', 'Travel')], default='World', max_length=30)),
                ('excerpt', models.TextField(null=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], default='PUBLISHED', max_length=30)),
                ('content', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_api.post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
