# Generated by Django 3.2.8 on 2022-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_auto_20220605_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
