# Generated by Django 3.2.8 on 2022-03-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50)),
                ('follower_username', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_img', models.ImageField(default='default_profile_image.png', upload_to='profile_images')),
                ('about_you', models.TextField()),
                ('country', models.CharField(blank=True, max_length=50)),
                ('social_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
